// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/document_chunk.dart';
import 'data/source_document.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5484652733667369701),
    name: 'DocumentChunk',
    lastPropertyId: const obx_int.IdUid(8, 2807595413600647608),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2282764870882905147),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5482550389560550236),
        name: 'documentId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 5727559826318858788),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4747886574057010492),
        name: 'sourceLabel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1695121407116413204),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6244343848132142397),
        name: 'startOffset',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8474867045646723907),
        name: 'chunkIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4262172345974431594),
        name: 'embeddingCsv',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2807595413600647608),
        name: 'createdAt',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7567170916753899068),
    name: 'SourceDocument',
    lastPropertyId: const obx_int.IdUid(9, 2873061965285916338),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3843753301245440298),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7384662189584211423),
        name: 'documentId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 8345200490917283017),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6405005799693533864),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4047958061348622038),
        name: 'fileType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4658546399582292418),
        name: 'totalChunks',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 463596404952317756),
        name: 'fileSizeBytes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 298234476052350381),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 98131793694572237),
        name: 'createdAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2873061965285916338),
        name: 'updatedAt',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 7567170916753899068),
    lastIndexId: const obx_int.IdUid(2, 8345200490917283017),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    DocumentChunk: obx_int.EntityDefinition<DocumentChunk>(
      model: _entities[0],
      toOneRelations: (DocumentChunk object) => [],
      toManyRelations: (DocumentChunk object) => {},
      getId: (DocumentChunk object) => object.id,
      setId: (DocumentChunk object, int id) {
        object.id = id;
      },
      objectToFB: (DocumentChunk object, fb.Builder fbb) {
        final documentIdOffset = fbb.writeString(object.documentId);
        final sourceLabelOffset = fbb.writeString(object.sourceLabel);
        final textOffset = fbb.writeString(object.text);
        final embeddingCsvOffset = fbb.writeString(object.embeddingCsv);
        final createdAtOffset = fbb.writeString(object.createdAt);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, documentIdOffset);
        fbb.addOffset(2, sourceLabelOffset);
        fbb.addOffset(3, textOffset);
        fbb.addInt64(4, object.startOffset);
        fbb.addInt64(5, object.chunkIndex);
        fbb.addOffset(6, embeddingCsvOffset);
        fbb.addOffset(7, createdAtOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = DocumentChunk()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..documentId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..sourceLabel = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..text = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..startOffset = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          )
          ..chunkIndex = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            14,
            0,
          )
          ..embeddingCsv = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..createdAt = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 18, '');

        return object;
      },
    ),
    SourceDocument: obx_int.EntityDefinition<SourceDocument>(
      model: _entities[1],
      toOneRelations: (SourceDocument object) => [],
      toManyRelations: (SourceDocument object) => {},
      getId: (SourceDocument object) => object.id,
      setId: (SourceDocument object, int id) {
        object.id = id;
      },
      objectToFB: (SourceDocument object, fb.Builder fbb) {
        final documentIdOffset = fbb.writeString(object.documentId);
        final nameOffset = fbb.writeString(object.name);
        final fileTypeOffset = fbb.writeString(object.fileType);
        final statusOffset = fbb.writeString(object.status);
        final createdAtOffset = fbb.writeString(object.createdAt);
        final updatedAtOffset = fbb.writeString(object.updatedAt);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, documentIdOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, fileTypeOffset);
        fbb.addInt64(4, object.totalChunks);
        fbb.addInt64(5, object.fileSizeBytes);
        fbb.addOffset(6, statusOffset);
        fbb.addOffset(7, createdAtOffset);
        fbb.addOffset(8, updatedAtOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = SourceDocument()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..documentId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..fileType = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..totalChunks = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          )
          ..fileSizeBytes = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            14,
            0,
          )
          ..status = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..createdAt = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 18, '')
          ..updatedAt = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 20, '');

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DocumentChunk] entity fields to define ObjectBox queries.
class DocumentChunk_ {
  /// See [DocumentChunk.id].
  static final id = obx.QueryIntegerProperty<DocumentChunk>(
    _entities[0].properties[0],
  );

  /// See [DocumentChunk.documentId].
  static final documentId = obx.QueryStringProperty<DocumentChunk>(
    _entities[0].properties[1],
  );

  /// See [DocumentChunk.sourceLabel].
  static final sourceLabel = obx.QueryStringProperty<DocumentChunk>(
    _entities[0].properties[2],
  );

  /// See [DocumentChunk.text].
  static final text = obx.QueryStringProperty<DocumentChunk>(
    _entities[0].properties[3],
  );

  /// See [DocumentChunk.startOffset].
  static final startOffset = obx.QueryIntegerProperty<DocumentChunk>(
    _entities[0].properties[4],
  );

  /// See [DocumentChunk.chunkIndex].
  static final chunkIndex = obx.QueryIntegerProperty<DocumentChunk>(
    _entities[0].properties[5],
  );

  /// See [DocumentChunk.embeddingCsv].
  static final embeddingCsv = obx.QueryStringProperty<DocumentChunk>(
    _entities[0].properties[6],
  );

  /// See [DocumentChunk.createdAt].
  static final createdAt = obx.QueryStringProperty<DocumentChunk>(
    _entities[0].properties[7],
  );
}

/// [SourceDocument] entity fields to define ObjectBox queries.
class SourceDocument_ {
  /// See [SourceDocument.id].
  static final id = obx.QueryIntegerProperty<SourceDocument>(
    _entities[1].properties[0],
  );

  /// See [SourceDocument.documentId].
  static final documentId = obx.QueryStringProperty<SourceDocument>(
    _entities[1].properties[1],
  );

  /// See [SourceDocument.name].
  static final name = obx.QueryStringProperty<SourceDocument>(
    _entities[1].properties[2],
  );

  /// See [SourceDocument.fileType].
  static final fileType = obx.QueryStringProperty<SourceDocument>(
    _entities[1].properties[3],
  );

  /// See [SourceDocument.totalChunks].
  static final totalChunks = obx.QueryIntegerProperty<SourceDocument>(
    _entities[1].properties[4],
  );

  /// See [SourceDocument.fileSizeBytes].
  static final fileSizeBytes = obx.QueryIntegerProperty<SourceDocument>(
    _entities[1].properties[5],
  );

  /// See [SourceDocument.status].
  static final status = obx.QueryStringProperty<SourceDocument>(
    _entities[1].properties[6],
  );

  /// See [SourceDocument.createdAt].
  static final createdAt = obx.QueryStringProperty<SourceDocument>(
    _entities[1].properties[7],
  );

  /// See [SourceDocument.updatedAt].
  static final updatedAt = obx.QueryStringProperty<SourceDocument>(
    _entities[1].properties[8],
  );
}
